// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dealer.proto
#ifndef GRPC_dealer_2eproto__INCLUDED
#define GRPC_dealer_2eproto__INCLUDED

#include "dealer.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace Dealer {

// The greeting service definition.
class Game final {
 public:
  static constexpr char const* service_full_name() {
    return "Dealer.Game";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::Dealer::DealerRequest, ::Dealer::DealerRequest>> GameStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::Dealer::DealerRequest, ::Dealer::DealerRequest>>(GameStreamRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::Dealer::DealerRequest, ::Dealer::DealerRequest>> AsyncGameStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::Dealer::DealerRequest, ::Dealer::DealerRequest>>(AsyncGameStreamRaw(context, cq, tag));
    }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::Dealer::DealerRequest, ::Dealer::DealerRequest>* GameStreamRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::Dealer::DealerRequest, ::Dealer::DealerRequest>* AsyncGameStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::Dealer::DealerRequest, ::Dealer::DealerRequest>> GameStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::Dealer::DealerRequest, ::Dealer::DealerRequest>>(GameStreamRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::Dealer::DealerRequest, ::Dealer::DealerRequest>> AsyncGameStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::Dealer::DealerRequest, ::Dealer::DealerRequest>>(AsyncGameStreamRaw(context, cq, tag));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReaderWriter< ::Dealer::DealerRequest, ::Dealer::DealerRequest>* GameStreamRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::Dealer::DealerRequest, ::Dealer::DealerRequest>* AsyncGameStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    const ::grpc::RpcMethod rpcmethod_GameStream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status GameStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::Dealer::DealerRequest, ::Dealer::DealerRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_GameStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GameStream() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GameStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GameStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::Dealer::DealerRequest, ::Dealer::DealerRequest>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGameStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::Dealer::DealerRequest, ::Dealer::DealerRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GameStream<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_GameStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GameStream() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GameStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GameStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::Dealer::DealerRequest, ::Dealer::DealerRequest>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace Dealer


#endif  // GRPC_dealer_2eproto__INCLUDED
